name: discordPanda
on:
  push:
    branches: [main]
jobs:
    builds:
      runs-on: ubuntu-latest
      name: my build
      steps:
        - name: Discord Message
          uses: discord-actions/message@v2
          with:
            # A Discord webhook URL
            webhookUrl: https://discordapp.com/api/webhooks/1316956354786885673/TnLUfOQiSbcjinGjEXP44tQwVosbe8HGv_gviHMyIZYWbWlr4rcTYRDpNk24h2DO7pa5
            # A message to send to Discord
            message: "helloo happy friyay!!"
            
      
    
